CREATE DATABASE CourseWork_Krasnopolsky
GO
USE CourseWork_Krasnopolsky

CREATE TABLE [User]
(
	Id INT CONSTRAINT PK_User_Id PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	FirstName NVARCHAR(100) NOT NULL,
	Surname NVARCHAR(100),
	[Login] NVARCHAR(100) CONSTRAINT UQ_User_Login UNIQUE NOT NULL,
	[Password] NVARCHAR(100) NOT NULL
)

CREATE TABLE Goal
(
	Id INT CONSTRAINT PK_Goal_Id PRIMARY KEY IDENTITY NOT NULL,
	UserId INT CONSTRAINT FK_Goal_UserId FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500),
	IsCompleted BIT NOT NULL
)

CREATE TABLE Step
(
	Id INT CONSTRAINT PK_Step_Id PRIMARY KEY IDENTITY NOT NULL,
	GoalId INT CONSTRAINT FK_Step_GoalId FOREIGN KEY REFERENCES Goal(Id) NOT NULL,
	Title NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500),
	IsCompleted BIT NOT NULL
)
CREATE TABLE Token
(
	Id INT CONSTRAINT PK_Token_Id PRIMARY KEY IDENTITY NOT NULL,
	UserId INT CONSTRAINT FK_Token_UserId FOREIGN KEY REFERENCES [User](Id) NOT NULL,
	[Key] NVARCHAR(36) CONSTRAINT UQ_Token_Key UNIQUE NOT NULL,
	IsUsed BIT NOT NULL
)
GO
