CREATE DATABASE OnlineShop_Shadiev_Abduvokhidov
GO
USE OnlineShop_Shadiev_Abduvokhidov

CREATE TABLE Customer
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	SNP NVARCHAR(150) NOT NULL,
	[Email] VARCHAR(200) NOT NULL CHECK([Email] LIKE '%@%%.%')
);

CREATE TABLE Supplyer
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	Sity NVARCHAR(200) NOT NULL,
	[Address] NVARCHAR(200) NOT NULL
);
GO


CREATE TABLE Purchase
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	CustomerId INT FOREIGN KEY REFERENCES Customer(Id) NOT NULL,
);

CREATE TABLE Supply
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	SupplyerId INT FOREIGN KEY REFERENCES Supplyer(Id) NOT NULL,
	[Date] DATE NOT NULL
);

CREATE TABLE [Product]
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Title NVARCHAR(200) NOT NULL,
);
GO


CREATE TABLE Cost
(
	ProductId INT FOREIGN KEY REFERENCES [Product](Id) NOT NULL,
	[Date] DATE NOT NULL,
	[Value] MONEY,
	PRIMARY KEY(ProductId, [Date])
);

CREATE TABLE MagazinePurchase
(
	PurchaseId INT FOREIGN KEY REFERENCES Purchase(Id) NOT NULL,
	ProductId INT FOREIGN KEY REFERENCES [Product](Id) NOT NULL,
	[Count] INT NOT NULL,
	PRIMARY KEY(PurchaseId, ProductId)
);

CREATE TABLE MagazineSupply
(
	SupplyId INT FOREIGN KEY REFERENCES Supply(Id) NOT NULL,
	ProductId INT FOREIGN KEY REFERENCES [Product](Id) NOT NULL,
	[Count] INT NOT NULL,
	PRIMARY KEY(SupplyId, ProductId)
);